server:
  port: 8081
  servlet:
    context-path: /minioServer
spring:
  application:
    name: springboot-minio
  mvc:
    view:
      prefix: /WEB-INF/pages
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
minio:
  endpoint: http://172.16.7.12:9000
  accesskey: minioadmin
  secretKey: minioadmin
